import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { z } from 'zod';

import { findProjectRoot, AGENT_DIR } from '../config/settings.js';
import type { ToolSpec } from './types.js';
import { errorMessage } from './util.js';

const schema = z.object({
  plan: z.string().describe('The full implementation plan, in Markdown.'),
  title: z.string().optional().describe('Short title for the plan file name.'),
});

/**
 * Plan Mode's exit. Not in `builtinTools()` — the CLI only registers it when the
 * mode is `plan`, so the model never sees a tool it cannot use.
 *
 * The plan file is written straight through `fs` (not the `write` tool): it is
 * this tool's own designated output, always under `<projectRoot>/.agent/plans/`,
 * and not subject to the read-before-write invariant.
 */
export const exitPlanModeTool: ToolSpec<z.infer<typeof schema>> = {
  name: 'exit_plan_mode',
  description:
    'Call this when your implementation plan is ready, to hand it over for approval. ' +
    'Provide the full plan as Markdown. If approved you leave plan mode and begin implementing; ' +
    'if not, revise and call this again.',
  schema,
  readOnly: false,
  concurrencySafe: false,
  async execute(input, ctx) {
    const root = await findProjectRoot(ctx.cwd);
    const dir = join(root, AGENT_DIR, 'plans');
    const name = `${timestamp()}-${slug(input.title ?? firstLine(input.plan))}.md`;
    const path = join(dir, name);

    try {
      await mkdir(dir, { recursive: true });
      await writeFile(path, planDocument(input.title, input.plan), 'utf8');
    } catch (err) {
      return { content: `Could not write the plan file: ${errorMessage(err)}`, isError: true };
    }

    if (!ctx.control?.confirm) {
      // Non-interactive: there is no one to approve, so this is the end of the run.
      return { content: `Plan written to ${path}.`, endsRun: true };
    }

    const { approved, feedback } = await ctx.control.confirm({
      title: input.title ?? 'Implementation plan',
      body: input.plan,
    });

    if (approved) {
      const mode = ctx.control.exitPlanMode();
      return {
        content:
          `Plan approved and saved to ${path}. Permission mode is now "${mode}". ` +
          `Begin implementing the plan.`,
      };
    }

    return {
      content:
        `The user did not approve the plan.` +
        (feedback ? ` Feedback: ${feedback}` : '') +
        ` Revise it and call exit_plan_mode again — you are still in plan mode.`,
    };
  },
};

function planDocument(title: string | undefined, plan: string): string {
  const heading = title ? `# ${title}\n\n` : '';
  const stamp = `<!-- generated by exit_plan_mode at ${new Date().toISOString()} -->\n\n`;
  return `${heading}${stamp}${plan}\n`;
}

function firstLine(text: string): string {
  return text.split('\n').find((l) => l.trim() !== '') ?? 'plan';
}

function slug(text: string): string {
  const s = text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48);
  return s === '' ? 'plan' : s;
}

function timestamp(d = new Date()): string {
  const p = (n: number): string => String(n).padStart(2, '0');
  return (
    `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}` +
    `-${p(d.getHours())}${p(d.getMinutes())}`
  );
}
